# Copyright Contributors to the Open Cluster Management project

# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.org }}:{{ template "policy.fullname" . }}-config-policy
  labels:
    app: {{ template "policy.name" . }}
    chart: {{ template "policy.chart" . }}
    component: "policy"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "policy.fullname" . }}-config-policy
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.org }}:{{ template "policy.fullname" . }}-config-policy
  apiGroup: rbac.authorization.k8s.io
