# Copyright Contributors to the Open Cluster Management project

# Default values for application-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
org: open-cluster-management

enabled: true

hubKubeconfigSecret: null

clusterName: null
clusterNamespace: null

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 2Gi

global: 
  imagePullPolicy: Always 
  imagePullSecret: null
  imageOverrides: 
    multicluster_operators_subscription: quay.io/open-cluster-management/multicluster-operators-subscription:1.0.0
    klusterlet_addon_lease_controller: quay.io/open-cluster-management/klusterlet-addon-lease-controller:2.2.0
  nodeSelector: {}
